telegram:
  token: env
  bot_name: "pg_learn_bot"
  admin_accounts: env
spring:
  datasource:
    #url: jdbc:h2:mem:testdb
    url: jdbc:postgresql://localhost:5432/telegram_pg_learn_bot
    username: telegram_pg_learn_bot
    password: db
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
    defer-datasource-initialization: false
  sql:
    init:
      mode: never
      data-locations: data.sql
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml

  main:
    allow-circular-references: true
logging:
  file:
    name: logs\bot.log
    max-size: 1MB
    max-history: 10
  pattern:
    rolling-file-name:bot-%d{yyyy-MM-dd}.%i.log